// products.js
// Single source of truth for products across shop.html, luxury-handbags.html, product.html, etc.

window.PRODUCTS = [
  // BVOSBG series
  { img: "2.jpg",  name: "Monogrammed Crossbody", sku: "BVOSBG-001", desc: "22cm x 14cm x 5cm", price: "90,000 MMK", category: "Luxury Handbags" },
  { img: "3.jpg",  name: "Classic Saddle Bag", sku: "BVOSBG-002", desc: "22cm x 16cm x 6.5cm", price: "52,500 MMK", category: "Luxury Handbags" },
  { img: "4.jpg",  name: "Signature Crossbody", sku: "BVOSBG-003", desc: "25cm x 15cm x 10cm", price: "78,000 MMK", category: "Luxury Handbags" },
  { img: "5.jpg",  name: "Signature Hobo Bag", sku: "BVOSBG-004", desc: "26cm x 23cm x 9cm", price: "80,000 MMK", category: "Luxury Handbags" },
  { img: "6.jpg",  name: "Elegant Monogram Crossbody", sku: "BVOSBG-005", desc: "25cm x 17cm x 8cm", price: "83,000 MMK", category: "Luxury Handbags" },
  { img: "7.jpg",  name: "Chic Monogram Top Handle", sku: "BVOSBG-006", desc: "22cm x 16cm x 7cm", price: "77,000 MMK", category: "Luxury Handbags" },
  { img: "8.jpg",  name: "Classic Flap Shoulder Bag", sku: "BVOSBG-007", desc: "28cm x 15cm x 8cm", price: "75,000 MMK", category: "Luxury Handbags" },
  { img: "9.jpg",  name: "Vintage Chain Shoulder Bag", sku: "BVOSBG-008", desc: "30cm x 20cm x 9cm", price: "82,000 MMK", category: "Luxury Handbags" },
  { img: "10.jpg", name: "Midnight Glow Clutch", sku: "BVOSBG-009", desc: "23cm x 16cm x 8cm", price: "108,000 MMK", category: "Luxury Handbags" },
  { img: "11.jpg", name: "Stylish Stripe Crossbody", sku: "BVOSBG-010", desc: "22cm x 16cm x 9cm", price: "79,000 MMK", category: "Luxury Handbags" },
  { img: "12.jpg", name: "Vibrant Stripe Monogram", sku: "BVOSBG-011", desc: "22cm x 16cm x 9cm", price: "92,000 MMK", category: "Luxury Handbags" },
  { img: "13.jpg", name: "Chic Leather (Rabbit)", sku: "BVOSBG-012", desc: "25cm x 20cm x 10cm", price: "110,000 MMK", category: "Luxury Handbags" },
  { img: "14.jpg", name: "Classic Double Buckle", sku: "BVOSBG-013", desc: "25cm x 10cm x 20cm", price: "73,000 MMK", category: "Luxury Handbags" },
  { img: "15.jpg", name: "Classic MK Handbag", sku: "BVOSBG-014", desc: "26cm x 20cm x 12cm", price: "88,000 MMK", category: "Luxury Handbags" },
  { img: "16.jpg", name: "Scarlet Elegance Chain", sku: "BVOSBG-015", desc: "20cm x 15cm x 7cm", price: "74,000 MMK", category: "Luxury Handbags" },
  { img: "17.jpg", name: "Monogram Backpack Set", sku: "BVOSBG-016", desc: "27.5cm x 31cm", price: "115,000 MMK", category: "Luxury Handbags" },
  { img: "18.jpg", name: "Luxe Monogram Flap", sku: "BVOSBG-017", desc: "21cm x 14cm x 7cm", price: "77,000 MMK", category: "Luxury Handbags" },
  { img: "19.jpg", name: "Elegant Color-Block Tote", sku: "BVOSBG-018", desc: "38cm x 28.8cm", price: "79,000 MMK", category: "Luxury Handbags" },
  { img: "20.jpg", name: "Trendy Monogram Crossbody", sku: "BVOSBG-019", desc: "24cm x 14cm x 12cm", price: "66,000 MMK", category: "Luxury Handbags" },
  { img: "23.jpg", name: "Classic Monogram Satchel", sku: "BVOSBG-022", desc: "20cm x 17cm x 8cm", price: "93,000 MMK", category: "Luxury Handbags" },
  { img: "24.jpg", name: "Modern Leather Satchel", sku: "BVOSBG-023", desc: "29cm x 15cm x 9cm", price: "70,000 MMK", category: "Luxury Handbags" },
  { img: "25.jpg", name: "Luxe Leather Hobo", sku: "BVOSBG-024", desc: "28cm x 13cm x 20cm", price: "105,000 MMK", category: "Luxury Handbags" },
  { img: "26.jpg", name: "Heritage Monogram Satchel", sku: "BVOSBG-025", desc: "22cm x 16cm x 9cm", price: "87,000 MMK", category: "Luxury Handbags" },
  { img: "27.jpg", name: "Signature Saddle Crossbody", sku: "BVOSBG-026", desc: "22cm x 18cm x 6cm", price: "74,000 MMK", category: "Luxury Handbags" },
  { img: "28.jpg", name: "Luxe Leather Hobo (Large)", sku: "BVOSBG-027", desc: "42cm x 29cm x 10cm", price: "51,000 MMK", category: "Luxury Handbags" },
  { img: "29.jpg", name: "Elegant Chain Shoulder", sku: "BVOSBG-028", desc: "21cm x 14cm x 7cm", price: "84,000 MMK", category: "Luxury Handbags" },
  { img: "30.jpg", name: "Luxe Mini Crossbody", sku: "BVOSBG-029", desc: "20cm x 14cm x 5cm", price: "73,000 MMK", category: "Luxury Handbags" },
  { img: "31.jpg", name: "Smile Charm Mini Tote", sku: "BVOSBG-030", desc: "28cm x 25cm x 15cm", price: "80,000 MMK", category: "Luxury Handbags" },
  { img: "32.jpg", name: "Elegant Structured Top Handle", sku: "BVOSBG-031", desc: "25cm x 18cm x 8cm", price: "77,000 MMK", category: "Luxury Handbags" },
  { img: "33.jpg", name: "Stylish Mini Top Handle", sku: "BVOSBG-032", desc: "20cm x 17cm x 8cm", price: "80,000 MMK", category: "Luxury Handbags" },
  { img: "34.jpg", name: "Luxe Monogram Chain Crossbody", sku: "BVOSBG-033", desc: "20cm x 17cm x 8cm", price: "78,000 MMK", category: "Luxury Handbags" },
  { img: "35.jpg", name: "Classic Elegant Crossbody", sku: "BVOSBG-034", desc: "20cm x 14cm x 8cm", price: "88,500 MMK", category: "Luxury Handbags" },
  { img: "36.jpg", name: "Elegant Chain Strap Shoulder", sku: "BVOSBG-035", desc: "25cm x 15cm x 8cm", price: "88,500 MMK", category: "Luxury Handbags" },
  { img: "37.jpg", name: "Woven Leather Structured Handbag", sku: "BVOSBG-036", desc: "25cm x 18cm x 12cm", price: "79,000 MMK", category: "Luxury Handbags" },
  { img: "38.jpg", name: "Sleek Minimalist Hobo", sku: "BVOSBG-037", desc: "20cm x 17cm x 8cm", price: "78,000 MMK", category: "Luxury Handbags" },
  { img: "39.jpg", name: "Floral Chain Accent Shoulder", sku: "BVOSBG-038", desc: "20cm x 14cm x 8cm", price: "84,000 MMK", category: "Luxury Handbags" },
  { img: "40.jpg", name: "Elegant Gold Chain Quilted", sku: "BVOSBG-039", desc: "20cm x 17cm x 8cm", price: "90,000 MMK", category: "Luxury Handbags" },
  { img: "41.jpg", name: "Luxe Monogram Saddle Crossbody", sku: "BVOSBG-040", desc: "25cm x 18cm x 12cm", price: "84,000 MMK", category: "Luxury Handbags" },
  { img: "42.jpg", name: "Luxe Classic Leather Tote", sku: "BVOSBG-041", desc: "20cm x 17cm x 8cm", price: "92,000 MMK", category: "Luxury Handbags" },
  { img: "43.jpg", name: "Luxe Minimalist Leather Flap", sku: "BVOSBG-042", desc: "20cm x 17cm x 8cm", price: "80,000 MMK", category: "Luxury Handbags" },
  { img: "44.jpg", name: "Luxe Quilted Leather Chain", sku: "BVOSBG-043", desc: "20cm x 17cm x 8cm", price: "85,000 MMK", category: "Luxury Handbags" },
  { img: "45.jpg", name: "Monogram Vintage Crossbody", sku: "BVOSBG-044", desc: "20cm x 17cm x 8cm", price: "80,000 MMK", category: "Luxury Handbags" },
  { img: "46.jpg", name: "Quilted Chain Shoulder Bag", sku: "BVOSBG-045", desc: "20cm x 17cm x 8cm", price: "85,000 MMK", category: "Luxury Handbags" },
  { img: "47.jpg", name: "Elegant Mini Top Handle", sku: "BVOSBG-046", desc: "20cm x 17cm x 8cm", price: "80,000 MMK", category: "Luxury Handbags" },
  { img: "48.jpg", name: "Chic Leather Bucket Bag", sku: "BVOSBG-047", desc: "22cm x 17cm x 10cm", price: "80,000 MMK", category: "Luxury Handbags" },
  { img: "49.jpg", name: "Crocodile-Textured Mini Handbag", sku: "BVOSBG-048", desc: "17cm x 21cm x 8cm", price: "85,000 MMK", category: "Luxury Handbags" },
  { img: "50.jpg", name: "Vintage-Inspired Round Bag", sku: "BVOSBG-049", desc: "20cm x 18cm x 9cm", price: "95,000 MMK", category: "Luxury Handbags" },
  { img: "51.jpg", name: "Signature Monogram Structured Tote", sku: "BVOSBG-050", desc: "21cm x 13cm x 10cm", price: "85,000 MMK", category: "Luxury Handbags" },
  { img: "52.jpg", name: "Signature Monogram Structured Tote (Black)", sku: "BVOSBG-050", desc: "21cm x 13cm x 10cm", price: "85,000 MMK", category: "Luxury Handbags" },

  // BVBCFC series
  { img: "53.jpg", name: "Triomphe Leather Crossbody", sku: "BVBCFC-0011", desc: "Elegant design with gold hardware", price: "168,000 MMK", category: "Luxury Handbags" },
  { img: "54.jpg", name: "Signature Monogram Tote", sku: "BVBCFC-0005", desc: "Spacious design for daily essentials", price: "285,000 MMK", category: "Luxury Handbags" },
  { img: "55.jpg", name: "Vintage Half-Moon Shoulder Bag", sku: "BVBCFC-0018", desc: "Chic monogram with chain detail", price: "168,000 MMK", category: "Luxury Handbags" },
  { img: "56.jpg", name: "Elegant White Tote", sku: "BVBCFC-0021", desc: "Sophisticated design with gold accents", price: "168,000 MMK", category: "Luxury Handbags" },
  { img: "57.jpg", name: "Monogram Clutch with Chain", sku: "BVBCFC-0017", desc: "Compact and stylish for evenings", price: "225,000 MMK", category: "Luxury Handbags" },
  { img: "58.jpg", name: "Quilted Chain Handle Bag", sku: "BVBCFC-0014", desc: "Luxurious chevron quilting", price: "225,000 MMK", category: "Luxury Handbags" },
  { img: "59.jpg", name: "Dionysus Style Shoulder Bag", sku: "BVBCFC-008", desc: "Iconic buckle detail with chain strap", price: "225,000 MMK", category: "Luxury Handbags" },
  { img: "60.jpg", name: "Monogram Top Handle Satchel", sku: "BVBCFC-008", desc: "Structured design with signature print", price: "225,000 MMK", category: "Luxury Handbags" },
  { img: "61.jpg", name: "Crocodile Effect Top Handle", sku: "BVBCFC-0022", desc: "Available in vibrant colors", price: "225,000 MMK", category: "Luxury Handbags" },
  { img: "62.jpg", name: "Monogram Tote with Pouch", sku: "BVBCFC-007", desc: "Includes matching round coin purse", price: "168,000 MMK", category: "Luxury Handbags" },
  { img: "63.jpg", name: "Monogram Clutch with Chain", sku: "BVBCFC-0017", desc: "Stylish evening clutch", price: "225,000 MMK", category: "Luxury Handbags" },
  { img: "64.jpg", name: "Coach-Style Monogram Handbag", sku: "BVBCFC-006", desc: "Classic and elegant design", price: "225,000 MMK", category: "Luxury Handbags" },
  { img: "65.jpg", name: "Embossed Leather Tote", sku: "BVBCFC-0010", desc: "Spacious and sophisticated", price: "225,000 MMK", category: "Luxury Handbags" },
  { img: "66.jpg", name: "Monogram Top Handle Satchel", sku: "BVBCFC-0020", desc: "Elegant and structured", price: "200,000 MMK", category: "Luxury Handbags" },
  { img: "67.jpg", name: "Croc-Embossed Top Handle", sku: "BVBCFC-0022", desc: "Luxurious texture in black", price: "225,000 MMK", category: "Luxury Handbags" },
  { img: "68.jpg", name: "Quilted Mini Top Handle", sku: "BVBCFC-0023", desc: "Chic and feminine design", price: "285,000 MMK", category: "Luxury Handbags" }
];
